backend: &backend
  - '.github/workflows/test-backend.yml'
  - 'backend/**/*'
  - 'neo4j/**/*'
  - 'package.json'

docker: &docker
  - 'docker-compose.*'

webapp: &webapp
  - '.github/workflows/test-webapp.yml'
  - 'webapp/**/*'
  - 'package.json'

markdown: &markdown
  - '**/*.md'
  '.github/workflows/mlc_config.json'

vuepress: &vuepress
  - '.github/workflows/deploy-documentation.yml'
  - '.vuepress/**/*'
  - 'package.json'

documentation: &documentation
  - vuepress
  - markdown
