# These file filter patterns are used by the action https://github.com/dorny/paths-filter

frontend-test-lint-code: &frontend-test-lint-code
  - '**/*'

frontend-test-unit-code: &frontend-test-unit-code
  - '**/*'