name: ocelot.social check documentation

on: push

jobs:
  files-changed:
    name: Detect File Changes - Markdown files
    runs-on: ubuntu-latest
    outputs:
      markdown: ${{ steps.changes.outputs.markdown }}
      vuepress: ${{ steps.changes.outputs.vuepress }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Check for markdown file changes
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml
          list-files: shell

  check-markdown-links:
    name: Check Markdown links
    needs: files-changed
    runs-on: ubuntu-latest
    if: needs.files-changed.outputs.markdown == 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Check Markdown Links
      uses: gaurav-nelson/github-action-markdown-link-check@master
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'no'
        # at any .md file change take the chance to check the links in all .md files
        check-modified-files-only: 'no'
        config-file: '.github/workflows/mlc_config.json'
        base-branch: 'master'
        folder-path: '.'
