name: "frontend:deploy:chromatic"
on: [push]
#on:
#  push:
#    branches:
#      - master
jobs:
  build-and-deploy:
    name: Chromatic - Frontend
    runs-on: ubuntu-latest
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Frontend | Build
        run: npm install && npm run chromatic -- --exit-zero-on-changes